### ISSUE TITLE
NativeLinkedList SortingNodeMemoryAddresses() does not sort properly after inserting an intermediate node.

### ISSUE THREAD

**Issue by NeistH2o** [jacksondunstan/NativeCollections#15]
Hi there,

I have been trying very hard to figure out what I was doing wrong with the NativeLinkedList but I think I found a bug.

I duplicated the test `SortNodeMemoryAddressesPreservesOrderButSortsMemory` and create a new one like this:
```csharp
[Test]
public void SortNodeMemoryAddressesPreservesOrderButSortsMemoryRemoveAndInsertIntermediateNode()
{
	using (var list = new NativeLinkedList<int>(7, Allocator.Temp))
	{
		var e00 = list.InsertAfter(list.Tail, 0);
		var e10 = list.InsertAfter(list.Tail, 10);
		var e20 = list.InsertAfter(list.Tail, 20);
		var e30 = list.InsertAfter(list.Tail, 30);
		var e40 = list.InsertAfter(list.Tail, 40);
		var e50 = list.InsertAfter(list.Tail, 50);
		var e60 = list.InsertAfter(list.Tail, 60);
		// values = [ h-0, 10, 20, 30, 40, 50, 60-t ]

		list.Remove(e30);
		// values = [ h-0, 10, 20, 60-t, 40, 50, _ ]

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 20, 40, 50, 60-t, _ ]

		// Same as removing e20 but the enumerator is invalid at this point.
		list.Remove(list.GetEnumeratorAtIndex(2));
		// values = [ h-0, 10, 60-t, 40, 50, _, _ ]

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 40, 50, 60-t, _, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(40));
		Assert.That(list[3], Is.EqualTo(50));
		Assert.That(list[4], Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(60));
		AssertListValues(list, 0, 10, 40, 50, 60);

		var e15 = list.InsertAfter(list.GetEnumeratorAtIndex(1), 15);
		// values = [ h-0, 10, 40, 50, 60-t, 15, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(40));
		Assert.That(list[3], Is.EqualTo(50));
		Assert.That(list[4], Is.EqualTo(60));
		Assert.That(list[5], Is.EqualTo(15));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(15));
		AssertListValues(list, 0, 10, 15, 40, 50, 60);

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 15, 40, 50, 60-t, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(15));
		Assert.That(list[3], Is.EqualTo(40)); // ERROR HERE -> 50
		Assert.That(list[4], Is.EqualTo(50)); // ERROR HERE -> 60
		Assert.That(list[5], Is.EqualTo(60)); // ERROR HERE -> 40
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(15));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(40)); // ERROR HERE -> 50
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(50)); // ERROR HERE -> 60
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(60)); // ERROR HERE -> 40
		AssertListValues(list, 0, 10, 15, 40, 50, 60);

		AssertGeneralInvariants(list);
	}
}
```
Everything works fine until the very end where you can see the **ERROR HERE** followed by the value I'm getting.
As you can see it appears that the addresses after the one that was inserted have circled around, as if they all went up by one index, and the one at the first index became last.

I was able to fix that issue by modifying the for loop in `SortNodeMemoryAddresses` with the following:
```csharp
using (var temporaryBuffer = new NativeArray<T>(m_State -> m_Length, Allocator.Temp, NativeArrayOptions.UninitializedMemory))
{
	UnsafeUtility.MemCpy(temporaryBuffer.GetUnsafePtr(), m_State -> m_Values, (long) (m_State -> m_Length * UnsafeUtility.SizeOf<T>()));

	for (int nodeIndex = m_State -> m_HeadIndex, sequentialIndex = 0; nodeIndex >= 0; nodeIndex = m_State -> m_NextIndexes[nodeIndex], sequentialIndex++)
		UnsafeUtility.WriteArrayElement(m_State -> m_Values, sequentialIndex, temporaryBuffer[nodeIndex]);
}
```
Where I create a copy of all the values as they are in the memory and they rewrite them in sequential order, which works, but it allocates a native array every time the method is called.

Did I miss something and I am not using the linked list the right way? or is there indeed a problem when the sequential value is written at the node index?

Thank you very much in advance.

**Comment by jacksondunstan** [comment]
Thanks for reporting this bug! I've fixed it in 7ce59741593b89ef5db7191d6a4344ffabce2d41 and added your unit test to catch any future regressions. No additional allocation was necessary since the only issue was that the "current" pointer was being advanced when a swap occurred which prevented swapping in future iterations.

**Comment by NeistH2o** [comment]
Hi again, thank you very much for looking into it and sorry for getting back to it so late myself, I have used my alternative version for the time being and just tried your fix today.

As it turns out I'm still getting incoherent results with 2 test methods, both of them fail with the fix, you can find the same "ERROR HERE" comment on the first error I get with both.

I don't have the time to look further into it right now but I hope this helps :)

```csharp
[Test]
	public void SortNodeMemoryAddressesPreservesOrderButSortsMemoryRemoveIntermediateNode()
	{
		using var list = new NativeLinkedList<int>(7, Allocator.Temp);
		var e00 = list.InsertAfter(list.Tail, 0);
		var e10 = list.InsertAfter(list.Tail, 10);
		var e20 = list.InsertAfter(list.Tail, 20);
		var e30 = list.InsertAfter(list.Tail, 30);
		var e40 = list.InsertAfter(list.Tail, 40);
		var e50 = list.InsertAfter(list.Tail, 50);
		var e60 = list.InsertAfter(list.Tail, 60);
		// values = [ h-0, 10, 20, 30, 40, 50, 60-t ]

		AssertListValues(list, 0, 10, 20, 30, 40, 50, 60);

		list.Remove(e30);
		// values = [ h-0, 10, 20, 60-t, 40, 50, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(20));
		Assert.That(list[3], Is.EqualTo(60));
		Assert.That(list[4], Is.EqualTo(40));
		Assert.That(list[5], Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(20));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(50));
		AssertListValues(list, 0, 10, 20, 40, 50, 60);

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 20, 40, 50, 60-t, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(20));
		Assert.That(list[3], Is.EqualTo(40));
		Assert.That(list[4], Is.EqualTo(50));  // ERROR HERE -> 60
		Assert.That(list[5], Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(20));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(60));
		AssertListValues(list, 0, 10, 20, 40, 50, 60);

		list.Remove(list.GetEnumeratorAtIndex(2));
		// values = [ h-0, 10, 60-t, 40, 50, _, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(60));
		Assert.That(list[3], Is.EqualTo(40));
		Assert.That(list[4], Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(50));
		AssertListValues(list, 0, 10, 40, 50, 60);

		var e5 = list.InsertAfter(list.Tail, 5);
		// values = [ h-0, 10, 60, 40, 50, 5-t, _ ]

		var e6 = list.InsertAfter(list.Tail, 6);
		// values = [ h-0, 10, 60, 40, 50, 5, 6-t ]

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 40, 50, 60, 5, 6-t ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(40));
		Assert.That(list[3], Is.EqualTo(50));
		Assert.That(list[4], Is.EqualTo(60));
		Assert.That(list[5], Is.EqualTo(5));
		Assert.That(list[6], Is.EqualTo(6));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(5));
		Assert.That(list.GetEnumeratorAtIndex(6).Current, Is.EqualTo(6));
		AssertListValues(list, 0, 10, 40, 50, 60, 5, 6);

		AssertGeneralInvariants(list);
	}

	[Test]
	public void SortNodeMemoryAddressesPreservesOrderButSortsMemoryRemoveAndInsertIntermediateNode()
	{
		using var list = new NativeLinkedList<int>(7, Allocator.Temp);
		var e00 = list.InsertAfter(list.Tail, 0);
		var e10 = list.InsertAfter(list.Tail, 10);
		var e20 = list.InsertAfter(list.Tail, 20);
		var e30 = list.InsertAfter(list.Tail, 30);
		var e40 = list.InsertAfter(list.Tail, 40);
		var e50 = list.InsertAfter(list.Tail, 50);
		var e60 = list.InsertAfter(list.Tail, 60);
		// values = [ h-0, 10, 20, 30, 40, 50, 60-t ]

		AssertListValues(list, 0, 10, 20, 30, 40, 50, 60);

		list.Remove(e30);
		// values = [ h-0, 10, 20, 60-t, 40, 50, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(20));
		Assert.That(list[3], Is.EqualTo(60));
		Assert.That(list[4], Is.EqualTo(40));
		Assert.That(list[5], Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(20));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(50));
		AssertListValues(list, 0, 10, 20, 40, 50, 60);

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 20, 40, 50, 60-t, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(20));
		Assert.That(list[3], Is.EqualTo(40));
		Assert.That(list[4], Is.EqualTo(50));  // ERROR HERE -> 60
		Assert.That(list[5], Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(20));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(60));
		AssertListValues(list, 0, 10, 20, 40, 50, 60);

		list.Remove(list.GetEnumeratorAtIndex(2));
		// values = [ h-0, 10, 60-t, 40, 50, _, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(60));
		Assert.That(list[3], Is.EqualTo(40));
		Assert.That(list[4], Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(50));
		AssertListValues(list, 0, 10, 40, 50, 60);

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 40, 50, 60-t, _, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(40));
		Assert.That(list[3], Is.EqualTo(50));
		Assert.That(list[4], Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(60));
		AssertListValues(list, 0, 10, 40, 50, 60);

		var e15 = list.InsertAfter(list.GetEnumeratorAtIndex(1), 15);
		// values = [ h-0, 10, 40, 50, 60-t, 15, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(40));
		Assert.That(list[3], Is.EqualTo(50));
		Assert.That(list[4], Is.EqualTo(60));
		Assert.That(list[5], Is.EqualTo(15));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(15));
		AssertListValues(list, 0, 10, 15, 40, 50, 60);

		list.SortNodeMemoryAddresses();
		// values = [ h-0, 10, 15, 40, 50, 60-t, _ ]

		Assert.That(list[0], Is.EqualTo(0));
		Assert.That(list[1], Is.EqualTo(10));
		Assert.That(list[2], Is.EqualTo(15));
		Assert.That(list[3], Is.EqualTo(40));
		Assert.That(list[4], Is.EqualTo(50));
		Assert.That(list[5], Is.EqualTo(60));
		Assert.That(list.GetEnumeratorAtIndex(0).Current, Is.EqualTo(0));
		Assert.That(list.GetEnumeratorAtIndex(1).Current, Is.EqualTo(10));
		Assert.That(list.GetEnumeratorAtIndex(2).Current, Is.EqualTo(15));
		Assert.That(list.GetEnumeratorAtIndex(3).Current, Is.EqualTo(40));
		Assert.That(list.GetEnumeratorAtIndex(4).Current, Is.EqualTo(50));
		Assert.That(list.GetEnumeratorAtIndex(5).Current, Is.EqualTo(60));
		AssertListValues(list, 0, 10, 15, 40, 50, 60);

		AssertGeneralInvariants(list);
	}
```

**Comment by NeistH2o** [comment]
Both methods show the same error, I don't remember very well why I made two methods that seemingly test the same things 🥲

**Comment by jacksondunstan** [comment]
@NeistH2o Thanks for following up and especially with the unit test showing the error! I revisited this function and fixed the issue by swapping nodes and their links during the sort, which resolves the issue where wrong links were taken due to only swapping values. This moved the link fixup inside the sort rather than afterward, which now just fixes up the head and tail pointers. The algorithm is still O(N) with no additional allocations ("in place") so perf should be good. :)

Fix commit: d377dd3a99d07ff73f1d0b981a7c38767d3df5e1
